// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file model-optimized-quantized.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace UnoOnnx
{
    
    public sealed class Input
    {
        public TensorInt64Bit input_ids; // shape(-1,-1)
        public TensorInt64Bit attention_mask; // shape(-1,-1)
    }
    
    public sealed class Output
    {
        public TensorFloat output_0; // shape(-1,-1,9)
    }
    
    public sealed class Model
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<Model> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            Model learningModel = new Model();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<Output> EvaluateAsync(Input input)
        {
            binding.Bind("input_ids", input.input_ids);
            binding.Bind("attention_mask", input.attention_mask);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new Output();
            output.output_0 = result.Outputs["output_0"] as TensorFloat;
            return output;
        }
    }
}

